CREATE OR REPLACE TRIGGER BEFORE_INSERT_SUB
  BEFORE INSERT OR UPDATE OF UNIT_COST, S_COUNT
  ON POS_SUB_ITEM
  FOR EACH ROW
  WHEN (NEW.UNIT_COST < 0 OR NEW.S_COUNT < 0)
BEGIN
    raise_application_error(-20052, 'INVALID INPUT: NEGATIVE OR STRING!!!');
  END;
/

