CREATE TRIGGER BEFORE_PASS_CHANGE
  BEFORE INSERT OR UPDATE OF PASSWORD
  ON POS_USER
  FOR EACH ROW
  BEGIN
    VERIFY_REQUIREMENTS(:new.username, :new.password);
  END;
/

drop TRIGGER BEFORE_PASS_CHANGE